# Generated by Django 2.1.7 on 2019-03-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('thing_uuid', models.CharField(max_length=36)),
                ('action_id', models.CharField(max_length=64)),
                ('data', models.TextField()),
            ],
        ),
    ]
