# Generated by Django 2.1.7 on 2019-03-06 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wotclient', '0002_authorizationmethod'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThingAuthorization',
            fields=[
                ('thing_uuid', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('authorization_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wotclient.AuthorizationMethod')),
            ],
        ),
    ]
